# Generated by Django 2.1.5 on 2019-02-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SepalLengthCm', models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Compr. da Sépala')),
                ('SepalWidthCm', models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Largura da Sépala')),
                ('PetalLengthCm', models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Compr. da Petula')),
                ('PetalWidthCm', models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Largura da Petula')),
                ('Species', models.CharField(blank=True, default=None, max_length=30, verbose_name='Espécie')),
            ],
            options={
                'verbose_name': 'Espécie',
                'verbose_name_plural': 'Espécies',
                'db_table': 'tb_ml_iris',
            },
        ),
        migrations.CreateModel(
            name='tb_ml_acoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, default=None, max_length=10, verbose_name='Data')),
                ('open', models.DecimalField(decimal_places=4, default=None, max_digits=10, verbose_name='Abertura')),
                ('max', models.DecimalField(decimal_places=4, default=None, max_digits=10, verbose_name='Valor Máximo')),
                ('min', models.DecimalField(decimal_places=4, default=None, max_digits=10, verbose_name='Valor Mínimo')),
                ('close', models.DecimalField(decimal_places=4, default=None, max_digits=10, verbose_name='Valor do Fechamento')),
                ('adj_close', models.DecimalField(decimal_places=4, default=None, max_digits=10, verbose_name='Preço Ajustado Fechamento')),
                ('volume', models.IntegerField(default=None, verbose_name='Volume de Transações')),
            ],
            options={
                'verbose_name': 'Regresão Linear',
                'db_table': 'tb_ml_acoes',
            },
        ),
    ]
