# Generated by Django 2.1.1 on 2019-01-21 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('MachineLearning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iris',
            name='SepalLengthCm',
        ),
    ]
