# Generated by Django 2.1.1 on 2019-01-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('MachineLearning', '0002_remove_iris_sepallengthcm'),
    ]

    operations = [
        migrations.AddField(
            model_name='iris',
            name='PetalLengthCm',
            field=models.FloatField(default=None, verbose_name='Cmprimento da Petula em cm'),
        ),
        migrations.AddField(
            model_name='iris',
            name='PetalWidthCm',
            field=models.FloatField(default=None, verbose_name='Largura da Petula em cm'),
        ),
        migrations.AddField(
            model_name='iris',
            name='SepalLengthCm',
            field=models.FloatField(default=None, verbose_name='Comprimento da Sépala em cm'),
        ),
        migrations.AddField(
            model_name='iris',
            name='SepalWidthCm',
            field=models.FloatField(default=None, verbose_name='Largura da Sépala em cm'),
        ),
        migrations.AlterField(
            model_name='iris',
            name='Species',
            field=models.CharField(default=None, max_length=30, verbose_name='Espécie'),
        ),
    ]
