# Generated by Django 2.1.5 on 2019-01-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('MachineLearning', '0003_auto_20190121_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iris',
            name='PetalLengthCm',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10,
                                      verbose_name='Compr. da Petula em cm'),
        ),
        migrations.AlterField(
            model_name='iris',
            name='PetalWidthCm',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10,
                                      verbose_name='Largura da Petula em cm'),
        ),
        migrations.AlterField(
            model_name='iris',
            name='SepalLengthCm',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10,
                                      verbose_name='Compr. da Sépala em cm'),
        ),
        migrations.AlterField(
            model_name='iris',
            name='SepalWidthCm',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10,
                                      verbose_name='Largura da Sépala em cm'),
        ),
        migrations.AlterField(
            model_name='iris',
            name='Species',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Espécie'),
        ),
    ]
