# Generated by Django 2.1.5 on 2019-02-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearning', '0004_auto_20190121_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iris',
            name='PetalLengthCm',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Compr. da Petula'),
        ),
        migrations.AlterField(
            model_name='iris',
            name='PetalWidthCm',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Largura da Petula'),
        ),
        migrations.AlterField(
            model_name='iris',
            name='SepalLengthCm',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Compr. da Sépala'),
        ),
        migrations.AlterField(
            model_name='iris',
            name='SepalWidthCm',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Largura da Sépala'),
        ),
        migrations.AlterModelTable(
            name='iris',
            table='tb_ml_iris',
        ),
    ]
