# Generated by Django 2.1.5 on 2019-02-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearning', '0005_auto_20190205_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_ml_preco_combustivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(blank=True, default=None, max_length=30, verbose_name='UF')),
                ('municipio', models.CharField(blank=True, default=None, max_length=100, verbose_name='Município')),
                ('data', models.CharField(blank=True, default=None, max_length=10, verbose_name='Data')),
                ('posto', models.CharField(blank=True, default=None, max_length=100, verbose_name='Posto')),
                ('bandeira', models.CharField(blank=True, default=None, max_length=50, verbose_name='Bandeira')),
                ('produto', models.CharField(blank=True, default=None, max_length=20, verbose_name='produto')),
                ('preco', models.DecimalField(decimal_places=4, default=None, max_digits=10, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Preços Combustiveis',
                'verbose_name_plural': 'Preço Combustível',
                'db_table': 'tb_ml_preco_combustível',
            },
        ),
    ]
