# Generated by Django 2.1.5 on 2019-02-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearning', '0006_tb_ml_preco_combustivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_ml_preco_combustivel',
            name='uf',
            field=models.CharField(blank=True, default=None, max_length=5, verbose_name='UF'),
        ),
    ]
