# Generated by Django 2.1.5 on 2019-02-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_ml_filmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_lançamento', models.CharField(blank=True, default=None, max_length=10, verbose_name='Ano Lançamento')),
                ('titulo_obra', models.CharField(blank=True, default=None, max_length=10, verbose_name='Título')),
                ('genero', models.CharField(blank=True, default=None, max_length=10, verbose_name='Gêneto')),
                ('pais_produtor_obra', models.CharField(blank=True, default=None, max_length=10, verbose_name='País Produtor da Obra')),
                ('nacionalidade_obra', models.CharField(blank=True, default=None, max_length=10, verbose_name='Nacionalidade')),
                ('data_lançamento', models.CharField(blank=True, default=None, max_length=10, verbose_name='Data Lançamento')),
                ('distribuidora', models.CharField(blank=True, default=None, max_length=10, verbose_name='Distribuidora')),
                ('salas_lançamento', models.IntegerField(default=None, verbose_name='Salas de Lançamento')),
                ('maximo_salas_ocupadas', models.IntegerField(default=None, verbose_name='Mámo de salas Ocupadas')),
                ('publico_acumulado', models.IntegerField(default=None, verbose_name='Publico Acumulado')),
                ('renda_acumulada', models.DecimalField(decimal_places=4, default=None, max_digits=10, verbose_name='Renda Acumulada')),
            ],
            options={
                'verbose_name': 'Sistema de Recomendação',
                'db_table': 'tb_ml_filmes',
            },
        ),
    ]
