# Generated by Django 2.1.1 on 2019-01-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SepalLengthCm', models.FloatField(verbose_name='Comprimento da Sépala em cm')),
                ('Species', models.CharField(max_length=30, verbose_name='Espécie')),
            ],
            options={
                'verbose_name': 'Espécie',
                'verbose_name_plural': 'Espécies',
            },
        ),
    ]
