# Generated by Django 2.1.5 on 2019-02-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0004_auto_20190206_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, default=None, max_length=10, verbose_name='Data')),
                ('open', models.DecimalField(decimal_places=4, default=None, max_digits=10, verbose_name='Valor na Abertura')),
                ('max', models.DecimalField(decimal_places=4, default=None, max_digits=10, verbose_name='Valor Máximo')),
                ('min', models.DecimalField(decimal_places=4, default=None, max_digits=10, verbose_name='Valor Mínimo')),
                ('close', models.DecimalField(decimal_places=4, default=None, max_digits=10, verbose_name='Valor do Fechamento')),
                ('adj_close', models.DecimalField(decimal_places=4, default=None, max_digits=10, verbose_name='Valor Ajustado no Fechamento')),
                ('volume', models.IntegerField(default=None, verbose_name='Volume de Transações')),
            ],
            options={
                'verbose_name': 'Regresão Linear',
                'db_table': 'tb_ml_acoes',
            },
        ),
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_lançamento', models.CharField(blank=True, default=None, max_length=10, verbose_name='Ano Lançamento')),
                ('titulo_obra', models.CharField(blank=True, default=None, max_length=200, verbose_name='Título')),
                ('genero', models.CharField(blank=True, default=None, max_length=50, verbose_name='Gêneto')),
                ('pais_produtor_obra', models.CharField(blank=True, default=None, max_length=100, verbose_name='País Produtor da Obra')),
                ('nacionalidade_obra', models.CharField(blank=True, default=None, max_length=100, verbose_name='Nacionalidade')),
                ('data_lançamento', models.CharField(blank=True, default=None, max_length=10, verbose_name='Data Lançamento')),
                ('distribuidora', models.CharField(blank=True, default=None, max_length=200, verbose_name='Distribuidora')),
                ('salas_lançamento', models.IntegerField(default=None, verbose_name='Salas de Lançamento')),
                ('maximo_salas_ocupadas', models.IntegerField(default=None, verbose_name='Mámo de salas Ocupadas')),
                ('publico_acumulado', models.IntegerField(default=None, verbose_name='Publico Acumulado')),
                ('renda_acumulada', models.FloatField(default=None, verbose_name='Renda Acumulada')),
            ],
            options={
                'verbose_name': 'Sistema de Recomendação',
                'db_table': 'tb_ml_filmes',
            },
        ),
        migrations.DeleteModel(
            name='tb_ml_acoes',
        ),
        migrations.DeleteModel(
            name='tb_ml_filmes',
        ),
    ]
